// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Backtop: typeof import('./components/Backtop/Backtop.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb/Breadcrumb.vue')['default']
    Clalendar: typeof import('./components/Clalendar/Clalendar.vue')['default']
    ContactIcon: typeof import('./components/ContactIcon/ContactIcon.vue')['default']
    Cover: typeof import('./components/Cover/Cover.vue')['default']
    Drag: typeof import('./components/Drag/Drag.vue')['default']
    Drawer: typeof import('./components/Drawer/Drawer.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FlowLayout: typeof import('./components/FlowLayout/FlowLayout.vue')['default']
    HeerHeader: typeof import('./components/HeerHeader/HeerHeader.vue')['default']
    Home: typeof import('./components/Home/Home.vue')['default']
    Introduce: typeof import('./components/Introduce/Introduce.vue')['default']
    MsgAlert: typeof import('./components/MsgAlert/MsgAlert.vue')['default']
    MsgConfirm: typeof import('./components/MsgC/MsgConfirm.vue')['default']
    NewArticle: typeof import('./components/NewArticle/NewArticle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./components/Side/Side.vue')['default']
    TimeLine: typeof import('./components/TimeLine/TimeLine.vue')['default']
  }

}
